# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Emanuele Relmi

services:
    spid-login:
        image: hub-spid-login-ms:local
        restart: unless-stopped
        ports:
            - "3001:3001"
        entrypoint:
            - /bin/sh
            - -c
            - |
                # decode the Base64-encoded PEMs into env vars
                echo "$SP_PRIVATE_KEY_B64" | base64 -d > /tmp/sp.key
                echo "$SP_PUBLIC_CERT_B64" | base64 -d > /tmp/sp.crt
                export SP_PRIVATE_KEY="$(cat /tmp/sp.key)"
                export SP_PUBLIC_CERT="$(cat /tmp/sp.crt)"
                # exec the image’s default command (Java jar)
                exec java -jar /opt/hub-spid-login-ms/app.jar
        environment:
            # Metadata URL for SPID IdP
            METADATA_URL:       "${METADATA_URL}"
            # Your SP’s entityID and Assertion Consumer Service URL
            SP_ENTITY_ID:       "${SP_ENTITY_ID}"
            ACS_URL:            "${ACS_URL}"
            # Secrets for session management and JWT signing
            SESSION_SECRET:     "${SESSION_SECRET}"
            JWT_SECRET:         "${JWT_SECRET}"